import 'src/styles/destyle.css'
import 'src/styles/globals.css'
import { Noto_Sans_JP, Roboto } from '@next/font/google'
import 'material-icons/iconfont/material-icons.css';
import { BaseTemplate } from '@/components/Templates/BaseTemplate'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: "swap",
  variable: "--font-roboto",
})

const notojp = Noto_Sans_JP({
  weight: ["500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-notojp",
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="jp">
      <body className={`
        ${roboto.variable}
        ${notojp.variable}
      `}>
        <BaseTemplate>
          {children}
        </BaseTemplate>
      </body>
    </html>
  )
}
